### ISSUE TITLE
如何对正在播放的hls流进行录制

### ISSUE THREAD

**Issue by dztec** [yangchao0033/HLS-Demo#4]
如何对正在播放的hls流进行录制，点击开始录制。。。。。然后点击保存，就将这一时间段的视频保存到本地

**Comment by yangchao0033** [comment]
@wojingwuyanyidui 你指的录制功能应该是对指定播放时间的视频进行保存，如果按 `HLS` 的方式，需要重新编辑 `m3u8` 的索引顺序。
